var express = require('express');
var router = express.Router();

var qp = require('flexqp');
qp.presetConnection(require('../dbconfig.json'));

var dbconfig = require('../dbconfig.json');
var emailer = require('../builder/emailBuilder');
var strings = require('node-strings');

module.exports = {
    emailsetter: async function () {
        try
        {
          console.log('reach autoemail');
          var temp = await qp.executeAndFetchPromise('select emailadd from cms.emails',[], dbconfig);
    
          console.log(temp);
          var targetEmail = temp[0].emailadd;
          var date = new Date();
          var current_hour = date.getHours();
          var temptext = '';
          var tempdeng = '';
      
          // grab some stuff from database NEED TO CHANGE 
      
          //placeholder
          var currentPsi = await qp.executeAndFetchPromise('select current from cms.psi',[],dbconfig);
          var currentCrime = await qp.executeAndFetchPromise('select * from cms.inreport where status = 1',[],dbconfig)
          var currentDengue = await qp.executeAndFetchPromise('select address from cms.dengue',[],dbconfig);

          for(let i = 0; i< currentCrime.length;i++)
          {
            temptext += '\n'+ currentCrime[i].title +' at '+currentCrime[i].location;
          }

          for(let i = 0; i< currentDengue.length;i++)
          {
            tempdeng += '\n'+ currentDengue[i].address;
          }

          console.log(temptext);
          var currentStatusEmail = emailer.email(targetEmail,"CMS Status Update at " +date,"\nCurrent PSI : "+currentPsi[0].current+"\n"+("\nActive Situations :")+temptext+"\n" +"\nDengue Hotspots : "+tempdeng+"\n\n\n\nThis is an autogenerated message, no messages will be checked by this email");
      
      
        }
        catch(error)
        {     
          console.log(error)
        }
      
    }
    
  }