var express = require('express');
var router = express.Router();

var qp = require('flexqp');
qp.presetConnection(require('../dbconfig.json'));

var dbconfig = require('../dbconfig.json');
var emailer = require('../builder/emailBuilder');

var nodemailer = require('nodemailer');


router.get('/', function (req, res, next) {
    res.render ('email', page = {"name":"email"});
});

router.post('/sendemail', async function (req, res, next)
{

  try
  {
    var temp = await qp.executeAndFetchPromise('select email from cms.pmo where PMO_ID = 1',[], dbconfig);

    console.log(temp[0].email)
    var targetEmail = temp[0].email;
    var date = new Date();
    var current_hour = date.getHours();

    // grab some stuff from database NEED TO CHANGE 

    //placeholder
    var currentPsi = 130;
    var currentCrime = 'Incident at tengah';
    var currentDengue = 'Bukit Temah Reserve'

    var currentStatusEmail = emailer.email(targetEmail,"CMS Status Update at " +date,"\nPSI : "+currentPsi+"\nTerrorist Activities : "+currentCrime+"\nDengue Hotspots : "+currentDengue+"\nThis is an autogenerated message, no messages will be checked by this email");
    res.render ('callcenter',  feedback= { "message": "email Sent" });


  }
  catch(error)
  {
    res.render ('callcenter',  feedback= { "message": "Unable to send email" });

  }

});


module.exports = router;